/* Ohlun'Joie — JS complet (Partie A) */
var eventsData={"evenements":[{"id":1,"titre":"Assemblée Générale Annuelle","date":"2025-10-20","heure":"18:30","description":"Assemblée générale annuelle avec présentation du bilan et vote sur les nouveaux projets de l'association.","lieu":"Salle municipale","type":"assemblée","image":"🏛️","maxParticipants":50,"inscriptions":[{"nom":"Dupont","prenom":"Marie","email":"marie.dupont@email.com","telephone":"06 12 34 56 78","commentaire":"Hâte de découvrir les nouveaux projets","participation":{"preparationSalle":true,"partieEvenement":false,"evenementEntier":true},"dateInscription":"2025-10-08"}]},{"id":2,"titre":"Atelier Cuisine d'Automne","date":"2025-11-15","heure":"14:00","description":"Découverte de la cuisine traditionnelle avec un chef local. Atelier pratique et dégustation.","lieu":"Centre culturel","type":"atelier","image":"👨‍🍳","maxParticipants":15,"inscriptions":[{"nom":"Leblanc","prenom":"Sophie","email":"sophie.leblanc@email.com","telephone":"06 34 56 78 90","commentaire":"J'adore cuisiner !","participation":{"preparationSalle":false,"partieEvenement":false,"evenementEntier":true},"dateInscription":"2025-10-07"}]},{"id":3,"titre":"Randonnée Hivernale","date":"2025-12-10","heure":"09:00","description":"Randonnée découverte dans la forêt enneigée. Niveau facile, vin chaud offert.","lieu":"Forêt des Vosges","type":"sport","image":"🥾","maxParticipants":25,"inscriptions":[]} ]};
var appConfig={"introText":"Notre association rassemble des bénévoles passionnés qui organisent des événements variés pour créer du lien social et enrichir la vie de notre commune. Ensemble, nous partageons des moments conviviaux et construisons une communauté solidaire.","logoUrl":"","eventTypes":["assemblée","atelier","sport","fête","conférence","événement"],"adminCredentials":{"email":"zinck.maxime@gmail.com","password":"Sto/nuqi0"}};
var currentView="timeline";var currentEvent=null;var isAdminLoggedIn=false;var currentAdminSection="events";
document.addEventListener("DOMContentLoaded",function(){wireBasics_A();loadStoredData_A();renderCurrentView_A();updateCountdown_A();setInterval(updateCountdown_A,60000);});

/* Utils A */
function byId_A(id){return document.getElementById(id);}function sortedEvents_A(){var a=eventsData.evenements.slice();a.sort(function(x,y){return new Date(x.date)-new Date(y.date);});return a;}function pct_A(n,d){return Math.min(100,Math.round((n/d)*100));}function color_A(p){return p>85?"#EF4444":(p>60?"#F59E0B":"#10B981");}

/* Wiring A */
function wireBasics_A(){var btns=document.querySelectorAll("[data-view]");for(var i=0;i<btns.length;i++){btns[i].addEventListener("click",function(e){switchView_A(e.currentTarget.getAttribute("data-view"));});}var adminBtn=byId_A("adminBtn");if(adminBtn){adminBtn.addEventListener("click",function(){var m=byId_A("loginModal");if(m){m.classList.remove("hidden");}});}document.addEventListener("click",function(e){if(e.target&&e.target.classList&&e.target.classList.contains("modal-overlay")){e.target.classList.add("hidden");}if(e.target&&e.target.classList&&e.target.classList.contains("modal-close")){closeAllModals_A();}});var loginForm=byId_A("loginForm");if(loginForm){loginForm.addEventListener("submit",handleLogin_A);}}

/* Switch + Render A */
function switchView_A(view){var btns=document.querySelectorAll("[data-view]");for(var i=0;i<btns.length;i++){var active=btns[i].getAttribute("data-view")===view;btns[i].classList.toggle("btn--primary",active);btns[i].classList.toggle("active",active);btns[i].classList.toggle("btn--outline",!active);}var cs=document.querySelectorAll(".events-container");for(var j=0;j<cs.length;j++){cs[j].classList.remove("active");}currentView=view;renderCurrentView_A();}
function renderCurrentView_A(){var c=byId_A(currentView+"View");if(c){c.classList.add("active");}if(currentView==="timeline"){renderTimeline_A();}else if(currentView==="list"){byId_A("listView").innerHTML="<div class='list-body' style='padding:16px;color:#6b7280;'>La vue Liste sera chargée après la Partie B.</div>";}else if(currentView==="cards"){byId_A("cardsView").innerHTML="<div class='cards-grid' style='padding:16px;color:#6b7280;'>La vue Cartes sera chargée après la Partie B.</div>";}}

/* Timeline A */
function renderTimeline_A(){var wrap=byId_A("timelineView");var evs=sortedEvents_A();wrap.innerHTML='<div class="timeline-rail"></div>';for(var i=0;i<evs.length;i++){wrap.appendChild(timelineEvent_A(evs[i]));}}
function timelineEvent_A(ev){var p=pct_A(ev.inscriptions.length,ev.maxParticipants);var full=ev.inscriptions.length>=ev.maxParticipants;var d=new Date(ev.date).toLocaleDateString("fr-FR",{day:"numeric",month:"long"});var c=color_A(p);var el=document.createElement("div");el.className="timeline-event";var list=ev.inscriptions.length?ev.inscriptions.map(function(pr){return '<div class="participant-item">'+pr.prenom+' '+pr.nom+'</div>';}).join(""):'<div class="participant-item" style="text-align:center;font-style:italic;">Aucune inscription</div>';el.innerHTML='<div class="timeline-content"><div class="timeline-dot"></div><div class="timeline-date">'+d+'</div><h3 style="font-size:1.25rem;font-weight:600;margin-bottom:0.75rem;color:#111827;">'+ev.image+' '+ev.titre+'</h3><div style="font-size:0.875rem;color:#4b5563;margin-bottom:1rem;"><div style="margin-bottom:0.25rem;">📅 '+ev.heure+' - 📍 '+ev.lieu+'</div><div>'+ev.description+'</div></div><div class="participants-gauge"><div class="gauge-container"><div class="gauge-bar"><div class="gauge-fill" style="width:'+p+'%;background-color:'+c+';"></div></div><span class="gauge-text">'+ev.inscriptions.length+'/'+ev.maxParticipants+'</span></div><div class="gauge-percentage">'+p+'% complet</div></div><div class="participants-dropdown"><button class="btn btn--outline dropdown-toggle" onclick="toggleParticipantsList_A('+ev.id+', this)">👥 Voir les inscrits <span>▼</span></button><div class="dropdown-content hidden" id="participantsA-'+ev.id+'">'+list+'</div></div><div style="margin-top:1rem;"><button class="btn '+(full?'btn--secondary':'btn--success')+'" '+(full?'disabled':'')+' onclick="openRegistrationModal_A('+ev.id+')">'+(full?'❌ Complet':'✅ S\'inscrire')+'</button></div></div>';return el;}
function toggleParticipantsList_A(id,btn){var dd=byId_A("participantsA-"+id);var arrow=btn.querySelector("span:last-child");var all=document.querySelectorAll(".dropdown-content");for(var i=0;i<all.length;i++){if(all[i]!==dd){all[i].classList.add("hidden");}}var arrows=document.querySelectorAll(".dropdown-toggle span:last-child");for(var j=0;j<arrows.length;j++){if(arrows[j]!==arrow){arrows[j].textContent="▼";}}var open=dd.classList.contains("hidden");dd.classList.toggle("hidden",!open);arrow.textContent=open?"▲":"▼";}

/* Admin login A */
function handleLogin_A(e){e.preventDefault();var email=byId_A("adminEmail").value;var password=byId_A("adminPassword").value;var err=byId_A("loginError");if(email===appConfig.adminCredentials.email&&password===appConfig.adminCredentials.password){isAdminLoggedIn=true;closeAllModals_A();byId_A("publicView").classList.add("hidden");byId_A("adminPanel").classList.remove("hidden");byId_A("configSection").classList.add("active");toast_A("Connexion réussie !");}else{err.classList.remove("hidden");byId_A("adminPassword").focus();}}
function closeAllModals_A(){var mods=document.querySelectorAll(".modal-overlay");for(var i=0;i<mods.length;i++){mods[i].classList.add("hidden");}var err=byId_A("loginError");if(err)err.classList.add("hidden");var pwd=byId_A("adminPassword");if(pwd)pwd.value="";currentEvent=null;}
function toast_A(m){var tm=byId_A("toastMessage");if(tm)tm.textContent=m;var t=byId_A("successToast");if(!t)return;t.classList.remove("hidden");t.classList.add("show");setTimeout(function(){t.classList.remove("show");setTimeout(function(){t.classList.add("hidden");},250);},2500);}

/* Countdown + Storage A /
function updateCountdown_A(){var now=new Date();var next=null;var evs=sortedEvents_A();for(var i=0;i<evs.length;i++){if(new Date(evs[i].date)>now){next=evs[i];break;}}var el=byId_A("countdownTimer");if(!el)return;if(!next){el.textContent="Aucun événement";return;}var d=Math.ceil((new Date(next.date)-now)/(1000606024));el.textContent=d===0?"Aujourd'hui !":(d===1?"Demain":d+" jours");}
function saveStoredData_A(){try{localStorage.setItem("ohlunjoie_events",JSON.stringify(eventsData));localStorage.setItem("ohlunjoie_config",JSON.stringify(appConfig));}catch(e){}}
function loadStoredData_A(){try{var e=localStorage.getItem("ohlunjoie_events");var c=localStorage.getItem("ohlunjoie_config");if(e)eventsData=JSON.parse(e);if(c)appConfig=JSON.parse(c);}catch(err){}var intro=byId_A("introText");if(intro)intro.textContent=appConfig.introText;}

/* Expose A */
window.toggleParticipantsList_A=toggleParticipantsList_A;window.openRegistrationModal_A=function(id){currentEvent=null;for(var i=0;i<eventsData.evenements.length;i++){if(eventsData.evenements[i].id===id){currentEvent=eventsData.evenements[i];break;}}if(!currentEvent)return;byId_A("registrationModal").classList.remove("hidden");byId_A("participationError").classList.add("hidden");};
