var eventsData={"evenements":[{"id":1,"titre":"Assemblée Générale Annuelle","date":"2025-10-20","heure":"18:30","description":"Assemblée générale annuelle avec présentation du bilan et vote sur les nouveaux projets de l'association.","lieu":"Salle municipale","type":"assemblée","image":"🏛️","maxParticipants":50,"inscriptions":[{"nom":"Dupont","prenom":"Marie","email":"marie.dupont@email.com","telephone":"06 12 34 56 78","commentaire":"Hâte de découvrir les nouveaux projets","participation":{"preparationSalle":true,"partieEvenement":false,"evenementEntier":true},"dateInscription":"2025-10-08"},{"nom":"Martin","prenom":"Paul","email":"paul.martin@email.com","telephone":"06 23 45 67 89","commentaire":"Disponible de 19h à 21h","participation":{"preparationSalle":false,"partieEvenement":true,"evenementEntier":false},"dateInscription":"2025-10-09"}]},{"id":2,"titre":"Atelier Cuisine d'Automne","date":"2025-11-15","heure":"14:00","description":"Découverte de la cuisine traditionnelle avec un chef local. Atelier pratique et dégustation.","lieu":"Centre culturel","type":"atelier","image":"👨‍🍳","maxParticipants":15,"inscriptions":[{"nom":"Leblanc","prenom":"Sophie","email":"sophie.leblanc@email.com","telephone":"06 34 56 78 90","commentaire":"J'adore cuisiner !","participation":{"preparationSalle":false,"partieEvenement":false,"evenementEntier":true},"dateInscription":"2025-10-07"}]},{"id":3,"titre":"Randonnée Hivernale","date":"2025-12-10","heure":"09:00","description":"Randonnée découverte dans la forêt enneigée. Niveau facile, vin chaud offert.","lieu":"Forêt des Vosges","type":"sport","image":"🥾","maxParticipants":25,"inscriptions":[]} ]};
var appConfig={"introText":"Notre association rassemble des bénévoles passionnés qui organisent des événements variés pour créer du lien social et enrichir la vie de notre commune. Ensemble, nous partageons des moments conviviaux et construisons une communauté solidaire.","logoUrl":"","eventTypes":["assemblée","atelier","sport","fête","conférence","événement"],"adminCredentials":{"email":"zinck.maxime@gmail.com","password":"Sto/nuqi0"}};
var currentView="timeline";var currentEvent=null;var isAdminLoggedIn=false;

document.addEventListener('DOMContentLoaded',function(){wire();loadStored();renderCurrent();updateCountdown();setInterval(updateCountdown,60000);});

/* Utils */
function $(id){return document.getElementById(id);}function sorted(){var a=eventsData.evenements.slice();a.sort(function(x,y){return new Date(x.date)-new Date(y.date);});return a;}function pct(n,d){return Math.min(100,Math.round((n/d)*100));}function col(p){return p>85?"#EF4444":(p>60?"#F59E0B":"#10B981");}

/* Wiring */
function wire(){var btns=document.querySelectorAll('[data-view]');for(var i=0;i<btns.length;i++){btns[i].addEventListener('click',function(e){switchView(e.currentTarget.getAttribute('data-view'));});}var adminBtn=$('adminBtn');if(adminBtn){adminBtn.addEventListener('click',function(){var m=$('loginModal');if(m){m.classList.remove('hidden');}});}document.addEventListener('click',function(e){if(e.target&&e.target.classList&&e.target.classList.contains('modal-overlay')){e.target.classList.add('hidden');}if(e.target&&e.target.classList&&e.target.classList.contains('modal-close')){closeModals();}});var loginForm=$('loginForm');if(loginForm){loginForm.addEventListener('submit',handleLogin);}var regForm=$('registrationForm');if(regForm){regForm.addEventListener('submit',handleRegistration);}var logoUpload=$('logoUpload');if(logoUpload){logoUpload.addEventListener('change',handleLogoUpload);}var removeLogo=$('removeLogo');if(removeLogo){removeLogo.addEventListener('click',removeLogoFn);}var saveIntro=$('saveIntroText');if(saveIntro){saveIntro.addEventListener('click',saveIntroText);}var addType=$('addEventType');if(addType){addType.addEventListener('click',addEventType);}}

/* Views */
function switchView(view){var btns=document.querySelectorAll('[data-view]');for(var i=0;i<btns.length;i++){var a=btns[i].getAttribute('data-view')===view;btns[i].classList.toggle('btn--primary',a);btns[i].classList.toggle('active',a);btns[i].classList.toggle('btn--outline',!a);}var cs=document.querySelectorAll('.events-container');for(var j=0;j<cs.length;j++){cs[j].classList.remove('active');}currentView=view;renderCurrent();}
function renderCurrent(){var c=$(currentView+'View');if(c){c.classList.add('active');}if(currentView==='timeline'){renderTimeline();}else if(currentView==='list'){renderList();}else if(currentView==='cards'){renderCards();}}

/* Timeline */
function renderTimeline(){var wrap=$('timelineView');var evs=sorted();wrap.innerHTML='<div class="timeline-rail"></div>';for(var i=0;i<evs.length;i++){wrap.appendChild(timelineEvent(evs[i]));}}
function timelineEvent(ev){var p=pct(ev.inscriptions.length,ev.maxParticipants);var full=ev.inscriptions.length>=ev.maxParticipants;var d=new Date(ev.date).toLocaleDateString('fr-FR',{day:'numeric',month:'long'});var c=col(p);var el=document.createElement('div');el.className='timeline-event';var list=ev.inscriptions.length?ev.inscriptions.map(function(pr){return '<div class="participant-item">'+pr.prenom+' '+pr.nom+'</div>';}).join(''):'<div class="participant-item" style="text-align:center;font-style:italic;">Aucune inscription</div>';el.innerHTML='<div class="timeline-content"><div class="timeline-dot"></div><div class="timeline-date">'+d+'</div><h3 style="font-size:1.25rem;font-weight:600;margin-bottom:0.75rem;color:#111827;">'+ev.image+' '+ev.titre+'</h3><div style="font-size:0.875rem;color:#4b5563;margin-bottom:1rem;"><div style="margin-bottom:0.25rem;">📅 '+ev.heure+' - 📍 '+ev.lieu+'</div><div>'+ev.description+'</div></div><div class="participants-gauge"><div class="gauge-container"><div class="gauge-bar"><div class="gauge-fill" style="width:'+p+'%;background-color:'+c+';"></div></div><span class="gauge-text">'+ev.inscriptions.length+'/'+ev.maxParticipants+'</span></div><div class="gauge-percentage">'+p+'% complet</div></div><div class="participants-dropdown"><button class="btn btn--outline dropdown-toggle" onclick="toggleParticipants('+ev.id+', this)">👥 Voir les inscrits <span>▼</span></button><div class="dropdown-content hidden" id="participants-'+ev.id+'">'+list+'</div></div><div style="margin-top:1rem;"><button class="btn '+(full?'btn--secondary':'btn--success')+'" '+(full?'disabled':'')+' onclick="openReg('+ev.id+')">'+(full?'❌ Complet':'✅ S\'inscrire')+'</button></div></div>';return el;}
function toggleParticipants(id,btn){var dd=$('participants-'+id);var arrow=btn.querySelector('span:last-child');var all=document.querySelectorAll('.dropdown-content');for(var i=0;i<all.length;i++){if(all[i]!==dd){all[i].classList.add('hidden');}}var arrows=document.querySelectorAll('.dropdown-toggle span:last-child');for(var j=0;j<arrows.length;j++){if(arrows[j]!==arrow){arrows[j].textContent='▼';}}var open=dd.classList.contains('hidden');dd.classList.toggle('hidden',!open);arrow.textContent=open?'▲':'▼';}

/* List */
function renderList(){var body=document.querySelector('#listView .list-body');if(!body){$('listView').innerHTML='<div class="list-body"></div>';body=document.querySelector('#listView .list-body');}body.innerHTML='';var evs=sorted();for(var i=0;i<evs.length;i++){body.appendChild(listEvent(evs[i]));}}
function listEvent(ev){var p=pct(ev.inscriptions.length,ev.maxParticipants);var full=ev.inscriptions.length>=ev.maxParticipants;var d=new Date(ev.date).toLocaleDateString('fr-FR',{day:'2-digit',month:'2-digit'});var c=col(p);var list=ev.inscriptions.length?ev.inscriptions.map(function(pr){return '<div class="participant-item">'+pr.prenom+' '+pr.nom+'</div>';}).join(''):'<div class="participant-item" style="text-align:center;font-style:italic;">Aucune inscription</div>';var el=document.createElement('div');el.className='list-event';el.innerHTML='<div>'+d+'
<small>'+ev.heure+'</small></div><div><strong>'+ev.titre+'</strong>
<button class="btn btn--outline" style="font-size:0.75rem;padding:0.25rem 0.5rem;margin-top:0.25rem;" onclick="toggleParticipants('+ev.id+', this)">👥 Inscrits <span>▼</span></button><div class="dropdown-content hidden" id="participants-'+ev.id+'">'+list+'</div></div><div>'+ev.lieu+'</div><div style="text-align:center;"><div class="gauge-container" style="margin-bottom:0.25rem;"><div class="gauge-bar" style="width:60px;height:6px;"><div class="gauge-fill" style="width:'+p+'%;background-color:'+c+';"></div></div></div><div style="font-size:0.75rem;">'+ev.inscriptions.length+'/'+ev.maxParticipants+'</div></div><div><button class="btn '+(full?'btn--secondary':'btn--success')+'" style="font-size:0.75rem;padding:0.25rem 0.5rem;" '+(full?'disabled':'')+' onclick="openReg('+ev.id+')">'+(full?'Complet':'S\'inscrire')+'</button></div>';return el;}

/* Cards */
function renderCards(){var grid=document.querySelector('#cardsView .cards-grid');if(!grid){$('cardsView').innerHTML='<div class="cards-grid"></div>';grid=document.querySelector('#cardsView .cards-grid');}grid.innerHTML='';var evs=sorted();for(var i=0;i<evs.length;i++){grid.appendChild(cardEvent(evs[i]));}}
function cardEvent(ev){var p=pct(ev.inscriptions.length,ev.maxParticipants);var full=ev.inscriptions.length>=ev.maxParticipants;var d=new Date(ev.date).toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long'});var c=col(p);var list=ev.inscriptions.length?ev.inscriptions.map(function(pr){return '<div class="participant-item">'+pr.prenom+' '+pr.nom+'</div>';}).join(''):'<div class="participant-item" style="text-align:center;font-style:italic;">Aucune inscription</div>';var el=document.createElement('div');el.className='event-card';el.innerHTML='<div class="card-header"><span class="card-icon">'+ev.image+'</span><div class="card-date">'+d+'</div><div>'+ev.heure+'</div></div><div class="card-body"><h3 class="card-title">'+ev.titre+'</h3><div class="card-location">📍 '+ev.lieu+'</div><p class="card-description">'+ev.description+'</p><div class="participants-gauge"><div class="gauge-container"><div class="gauge-bar"><div class="gauge-fill" style="width:'+p+'%;background-color:'+c+';"></div></div><span class="gauge-text">'+ev.inscriptions.length+'/'+ev.maxParticipants+'</span></div><div class="gauge-percentage">'+p+'% complet</div></div><div class="participants-dropdown"><button class="btn btn--outline dropdown-toggle" onclick="toggleParticipants('+ev.id+', this)">👥 Voir les inscrits <span>▼</span></button><div class="dropdown-content hidden" id="participants-'+ev.id+'">'+list+'</div></div><button class="btn '+(full?'btn--secondary':'btn--success')+'" style="width:100%;margin-top:0.75rem;" '+(full?'disabled':'')+' onclick="openReg('+ev.id+')">'+(full?'❌ Complet':'✅ S\'inscrire')+'</button></div>';return el;}

/* Admin + Registration */
function handleLogin(e){e.preventDefault();var email=$('adminEmail').value;var password=$('adminPassword').value;var err=$('loginError');if(email===appConfig.adminCredentials.email&&password===appConfig.adminCredentials.password){isAdminLoggedIn=true;closeModals();$('publicView').classList.add('hidden');$('adminPanel').classList.remove('hidden');loadConfig();toast('Connexion réussie !');}else{err.classList.remove('hidden');$('adminPassword').focus();}}
function openReg(id){currentEvent=null;for(var i=0;i<eventsData.evenements.length;i++){if(eventsData.evenements[i].id===id){currentEvent=eventsData.evenements[i];break;}}if(!currentEvent)return;$('registrationModal').classList.remove('hidden');$('participationError').classList.add('hidden');}
function handleRegistration(e){e.preventDefault();if(!currentEvent)return;var prep=$('preparationSalle').checked;var part=$('partieEvenement').checked;var all=$('evenementEntier').checked;var err=$('participationError');if(!prep&&!part&&!all){err.classList.remove('hidden');return;}err.classList.add('hidden');var reg={"nom":$('regLastName').value,"prenom":$('regFirstName').value,"email":$('regEmail').value,"telephone":$('regPhone').value,"commentaire":$('regComment').value,"participation":{"preparationSalle":prep,"partieEvenement":part,"evenementEntier":all},"dateInscription":new Date().toISOString().split('T')};currentEvent.inscriptions.push(reg);saveStored();closeModals();toast('Inscription confirmée !');renderCurrent();$('registrationForm').reset();}

/* Config /
function loadConfig(){$('introTextArea').value=appConfig.introText;renderTypes();updateLogo();}
function saveIntroText(){var t=$('introTextArea').value;if(t&&t.trim()){appConfig.introText=t;$('introText').textContent=t;saveStored();toast('Texte mis à jour');}}
function handleLogoUpload(e){var f=e.target.files&&e.target.files;if(!f)return;if(f.size>21024*1024){alert('Le fichier est trop volumineux (max 2MB)');return;}if(!/^image\/(png|jpeg|jpg|svg\+xml)$/.test(f.type)){alert('Format non supporté (PNG, JPG, JPEG, SVG uniquement)');return;}var r=new FileReader();r.onload=function(ev){appConfig.logoUrl=ev.target.result;updateLogo();saveStored();toast('Logo mis à jour');};r.readAsDataURL(f);}
function removeLogoFn(){appConfig.logoUrl="";updateLogo();saveStored();$('logoUpload').value="";toast('Logo supprimé');}
function updateLogo(){var el=$('associationLogo');if(!el)return;if(appConfig.logoUrl){el.innerHTML='<img src="'+appConfig.logoUrl+'" alt="Logo association" style="max-height:200px;width:auto;">';}else{el.textContent='🤝';}}
function renderTypes(){var c=$('eventTypesList');if(!c)return;c.innerHTML='';for(var i=0;i<appConfig.eventTypes.length;i++){var type=appConfig.eventTypes[i];var row=document.createElement('div');row.style.cssText='display:flex;justify-content:space-between;align-items:center;padding:0.5rem;background:#fff;border:1px solid #e5e7eb;border-radius:6px;margin-bottom:0.5rem;';var safe=type.replace(/'/g,"\'");row.innerHTML='<span>'+type+'</span><button class="btn btn--outline" style="font-size:0.75rem;padding:0.25rem 0.5rem;" onclick="removeType(\''+safe+'\')">🗑️ Supprimer</button>';c.appendChild(row);}}
function addEventType(){var input=$('newEventType');var v=(input.value||'').trim();if(!v)return;if(appConfig.eventTypes.indexOf(v)===-1){appConfig.eventTypes.push(v);input.value='';renderTypes();saveStored();toast('Type d\'événement ajouté');}}
function removeType(type){if(confirm('Supprimer le type "'+type+'" ?')){appConfig.eventTypes=appConfig.eventTypes.filter(function(t){return t!==type;});renderTypes();saveStored();toast('Type d\'événement supprimé');}}

/* Misc /
function updateCountdown(){var now=new Date();var next=null;var evs=sorted();for(var i=0;i<evs.length;i++){if(new Date(evs[i].date)>now){next=evs[i];break;}}var el=$('countdownTimer');if(!el)return;if(!next){el.textContent='Aucun événement';return;}var d=Math.ceil((new Date(next.date)-now)/(1000606024));el.textContent=d===0?"Aujourd'hui !":(d===1?'Demain':d+' jours');}
function closeModals(){var mods=document.querySelectorAll('.modal-overlay');for(var i=0;i<mods.length;i++){mods[i].classList.add('hidden');}var err=$('loginError');if(err)err.classList.add('hidden');var pwd=$('adminPassword');if(pwd)pwd.value='';currentEvent=null;}
function toast(m){var tm=$('toastMessage');if(tm)tm.textContent=m;var t=$('successToast');if(!t)return;t.classList.remove('hidden');t.classList.add('show');setTimeout(function(){t.classList.remove('show');setTimeout(function(){t.classList.add('hidden');},250);},2500);}
function saveStored(){try{localStorage.setItem('ohlunjoie_events',JSON.stringify(eventsData));localStorage.setItem('ohlunjoie_config',JSON.stringify(appConfig));}catch(e){}}
function loadStored(){try{var e=localStorage.getItem('ohlunjoie_events');var c=localStorage.getItem('ohlunjoie_config');if(e)eventsData=JSON.parse(e);if(c)appConfig=JSON.parse(c);}catch(err){}var intro=$('introText');if(intro)intro.textContent=appConfig.introText;updateLogo();}

/* Expose */
window.toggleParticipants=toggleParticipants;window.openReg=openReg;window.removeType=removeType;
